### ISSUE TITLE
classList is not working

### ISSUE THREAD

**Issue by vovacodes** [asbjornenge/testdom#6]
`Element#classList` is not working in `jsdom` and doesn't appear to be fixed in near future, maybe we should add some polyfill for it here?

**Comment by asbjornenge** [comment]
In version 1.0.0 we added support for additional globals (polyfills) via passing an additional object:

```
require('testdom')('<html><body></body></html>', {
    localStorage : 'localStorage',
})
console.log(localStorage)
```

That will do `global.localStorage = require('localStorage')` if no document exists. So adding a classList polyfill is as easy as finding one and doing the same :wink: 

Also; I encourage PR's with confirmed _additional globals_ in README.md -> https://github.com/asbjornenge/testdom#confirmed-modules

:+1:
