### ISSUE TITLE
Support for jsdom 5.0?

### ISSUE THREAD

**Issue by alfonsomunozpomer** [asbjornenge/testdom#7]
Are there any plans to support jsdom versions 4.0 or 5.0, taking into account that they dropped support for node and it’s io.js specific?

**Comment by asbjornenge** [comment]
Hm... good question. What about waiting for the node/io merge to complete and then make the jump?

**Comment by alfonsomunozpomer** [comment]
Yeah, sounds good. ;)

**Comment by asbjornenge** [comment]
:+1: I'll keep the issue open so I don't forget :stuck_out_tongue_closed_eyes: feel free to remind me :wink:

**Comment by asbjornenge** [comment]
@alfonsomunozpomer Alright, I think it's time to upgrade :wink: The io/node merge is complete and stable. `jsdom` is actually up to 6.5.1 now, so I'll be upgrading to that via #8

**Comment by asbjornenge** [comment]
It's out https://www.npmjs.com/package/testdom :tada: :smile:

**Comment by alfonsomunozpomer** [comment]
Fantastic! Thanks for being on the watch out.
